version: '3.8'

services:
  # Test databases
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chugr_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./shared/fixtures/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d chugr_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio-test:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: test_access_key
      MINIO_ROOT_PASSWORD: test_secret_key
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - minio_test_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  clickhouse-test:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8124:8123"
      - "9003:9000"
    volumes:
      - clickhouse_test_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: chugr_test
      CLICKHOUSE_USER: test_user
      CLICKHOUSE_PASSWORD: test_password
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test services (for integration tests)
  api-gateway-test:
    build:
      context: ../backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: test
      PORT: 3000
      JWT_SECRET: test_jwt_secret
      POSTGRES_URL: postgresql://test_user:test_password@postgres-test:5432/chugr_test
      REDIS_URL: redis://redis-test:6379
      MINIO_ENDPOINT: minio-test
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: test_access_key
      MINIO_SECRET_KEY: test_secret_key
      CLICKHOUSE_URL: http://clickhouse-test:8123
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      minio-test:
        condition: service_healthy
      clickhouse-test:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Security testing tools
  zap-proxy:
    image: owasp/zap2docker-stable:latest
    ports:
      - "8080:8080"
    volumes:
      - ./backend/security/zap:/zap/wrk
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true

volumes:
  postgres_test_data:
  redis_test_data:
  minio_test_data:
  clickhouse_test_data:
