version: '3.8'

services:
  # Test Databases Only
  postgres-test:
    image: postgres:15-alpine
    container_name: chugr-postgres-test
    environment:
      POSTGRES_DB: chugr_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d chugr_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chugr-test-network

  redis-test:
    image: redis:7-alpine
    container_name: chugr-redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - chugr-test-network

  minio-test:
    image: minio/minio:latest
    container_name: chugr-minio-test
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: test_access_key
      MINIO_ROOT_PASSWORD: test_secret_key
      MINIO_DEFAULT_BUCKETS: chugr-test-files,chugr-test-avatars
    ports:
      - "9011:9000"  # API
      - "9012:9001"  # Console
    volumes:
      - minio_test_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chugr-test-network

  clickhouse-test:
    image: clickhouse/clickhouse-server:latest
    container_name: chugr-clickhouse-test
    environment:
      CLICKHOUSE_DB: chugr_test
      CLICKHOUSE_USER: test_user
      CLICKHOUSE_PASSWORD: test_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8124:8123"  # HTTP
      - "9009:9009"  # Native
    volumes:
      - clickhouse_test_data:/var/lib/clickhouse
      - ./scripts/init-clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8124/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chugr-test-network

volumes:
  postgres_test_data:
    driver: local
  redis_test_data:
    driver: local
  minio_test_data:
    driver: local
  clickhouse_test_data:
    driver: local

networks:
  chugr-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
